import { usePromQuery } from '@/hooks/usePromQuery';
import { metricCatalog } from '@/config/metricCatalog';
import { KpiCard } from '@/components/panels/KpiCard';
import { PanelCard } from '@/components/panels/PanelCard';
import { PanelGrid } from '@/components/panels/PanelGrid';
import { LoadingSkeleton } from '@/components/panels/LoadingSkeleton';
import { TimeSeriesChart } from '@/components/charts/TimeSeriesChart';
import { PageHeader } from '@/components/primitives/PageHeader';
import { Section } from '@/components/primitives/Section';
import { HBarList } from '@/components/primitives/HBarList';
import { ArcGauge } from '@/components/primitives/ArcGauge';

function latestValue(data: ReturnType<typeof usePromQuery>['data']): number {
  const dp = data?.series[0]?.dataPoints;
  if (!dp || dp.length === 0) return 0;
  return parseFloat(dp[dp.length - 1]!.value) || 0;
}

function formatTokens(value: number): string {
  if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `${(value / 1000).toFixed(1)}K`;
  return value.toFixed(0);
}

export default function TokensPage() {
  const inputTokens = usePromQuery(metricCatalog['tokens_input_total']!.query);
  const outputTokens = usePromQuery(metricCatalog['tokens_output_total']!.query);
  const cacheRead = usePromQuery(metricCatalog['tokens_cache_read']!.query);
  const cacheWrite = usePromQuery(metricCatalog['tokens_cache_write']!.query);
  const inputRate = usePromQuery(metricCatalog['tokens_input_rate']!.query);
  const outputRate = usePromQuery(metricCatalog['tokens_output_rate']!.query);
  const byModel = usePromQuery(metricCatalog['tokens_by_model']!.query);
  const cacheHitRate = usePromQuery(metricCatalog['tokens_cache_hit_rate_ts']!.query);

  const anyLoading = inputTokens.isLoading || outputTokens.isLoading;

  if (anyLoading) {
    return (
      <div className="space-y-6">
        <PageHeader title="Tokens" subtitle="Token volume by model and agent" />
        <PanelGrid columns={4}>
          {Array.from({ length: 4 }).map((_, i) => <LoadingSkeleton key={i} />)}
        </PanelGrid>
      </div>
    );
  }

  const inputVal = latestValue(inputTokens.data);
  const cacheVal = latestValue(cacheRead.data);
  const outputVal = latestValue(outputTokens.data);
  const compositionTotal = inputVal + cacheVal + outputVal;

  const inputPct = compositionTotal > 0 ? (inputVal / compositionTotal) * 100 : 33;
  const cachePct = compositionTotal > 0 ? (cacheVal / compositionTotal) * 100 : 33;
  const outputPct = compositionTotal > 0 ? (outputVal / compositionTotal) * 100 : 34;

  return (
    <div className="space-y-6">
      <PageHeader title="Tokens" subtitle="Token volume by model and agent" />

      <Section title="Token Metrics" kicker="01">
        <PanelGrid columns={4}>
          <KpiCard
            title="Input Tokens"
            description="Total tokens sent to the LLM as prompt context across all sessions. Shows 0 when no agent conversations have occurred in the selected time range."
            value={formatTokens(inputVal)}
            sparklineData={inputTokens.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Output Tokens"
            description="Total tokens generated by the LLM in completions across all sessions. Shows 0 when no agent responses have been produced in the selected time range."
            value={formatTokens(outputVal)}
            sparklineData={outputTokens.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Cache Read"
            description="Tokens served from the prompt cache instead of being reprocessed by the LLM. Shows 0 when caching is disabled or no cache hits have occurred."
            value={formatTokens(cacheVal)}
            sparklineData={cacheRead.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Cache Write"
            description="Tokens written into the prompt cache for future reuse. Shows 0 when caching is disabled or no new cache entries have been created."
            value={formatTokens(latestValue(cacheWrite.data))}
            sparklineData={cacheWrite.data?.series[0]?.dataPoints}
          />
        </PanelGrid>
      </Section>

      <Section title="Throughput" kicker="02">
        <PanelGrid columns={2}>
          <PanelCard title="Input Token Rate" description="Tokens per minute">
            <TimeSeriesChart series={inputRate.data?.series ?? []} unit="tokens/min" />
          </PanelCard>
          <PanelCard title="Output Token Rate" description="Tokens per minute">
            <TimeSeriesChart series={outputRate.data?.series ?? []} unit="tokens/min" />
          </PanelCard>
        </PanelGrid>
      </Section>

      <Section title="Distribution" kicker="03">
        <PanelGrid columns={2}>
          <PanelCard title="Distribution by Model">
            <HBarList
              items={(byModel.data?.series ?? []).map((s) => ({
                label: s.labels['model'] ?? 'unknown',
                value: parseFloat(s.dataPoints[s.dataPoints.length - 1]?.value ?? '0'),
              }))}
              color="var(--otel-accent)"
              formatValue={(v) => formatTokens(v)}
            />
          </PanelCard>
          <PanelCard title="Cache Efficiency">
            <div className="flex items-center justify-center py-4">
              <ArcGauge
                value={latestValue(cacheHitRate.data)}
                max={1}
                size={140}
                color="var(--otel-positive)"
                label={`${(latestValue(cacheHitRate.data) * 100).toFixed(0)}%`}
                subtitle="cache hit rate"
                thickness={12}
              />
            </div>
          </PanelCard>
        </PanelGrid>
      </Section>

      <Section title="Token Composition" kicker="04">
        <div className="bg-card border border-border rounded-lg p-4">
          <div className="flex gap-0 h-6 rounded overflow-hidden mb-3">
            <div
              className="h-full bg-otel-info"
              style={{ width: `${inputPct}%` }}
            />
            <div
              className="h-full bg-otel-positive"
              style={{ width: `${cachePct}%` }}
            />
            <div
              className="h-full bg-otel-accent"
              style={{ width: `${outputPct}%` }}
            />
          </div>
          <div className="flex gap-6 text-xs font-mono tabular-nums">
            <span className="text-otel-info">● Input: {formatTokens(inputVal)}</span>
            <span className="text-otel-positive">● Cache: {formatTokens(cacheVal)}</span>
            <span className="text-otel-accent">● Output: {formatTokens(outputVal)}</span>
          </div>
        </div>
      </Section>
    </div>
  );
}
