import { usePromQuery } from '@/hooks/usePromQuery';
import { metricCatalog } from '@/config/metricCatalog';
import { KpiCard } from '@/components/panels/KpiCard';
import { PanelCard } from '@/components/panels/PanelCard';
import { PanelGrid } from '@/components/panels/PanelGrid';
import { LoadingSkeleton } from '@/components/panels/LoadingSkeleton';
import { TimeSeriesChart } from '@/components/charts/TimeSeriesChart';
import { PageHeader } from '@/components/primitives/PageHeader';
import { Section } from '@/components/primitives/Section';
import { HBarList } from '@/components/charts/HBarList';
import { MetricPanel } from '@/components/metrics/MetricPanel';
import {
  latestValue,
  formatKpi,
  seriesToBars,
} from '@/routes/Pulse/pulse-helpers';

export default function TokensPage() {
  const inputTokens = usePromQuery(metricCatalog['tokens_input_total']!.query);
  const outputTokens = usePromQuery(metricCatalog['tokens_output_total']!.query);
  const cacheRead = usePromQuery(metricCatalog['tokens_cache_read']!.query);
  const cacheWrite = usePromQuery(metricCatalog['tokens_cache_write']!.query);
  const inputRate = usePromQuery(metricCatalog['tokens_input_rate']!.query);
  const outputRate = usePromQuery(metricCatalog['tokens_output_rate']!.query);
  const byModel = usePromQuery(metricCatalog['tokens_by_model']!.query);
  const cacheHitRate = usePromQuery(metricCatalog['tokens_cache_hit_rate_ts']!.query);

  const anyLoading = inputTokens.isLoading || outputTokens.isLoading;

  if (anyLoading) {
    return (
      <div className="space-y-6">
        <PageHeader title="Tokens" subtitle="Token volume by model and agent" />
        <PanelGrid columns={4}>
          {Array.from({ length: 4 }).map((_, i) => <LoadingSkeleton key={i} />)}
        </PanelGrid>
      </div>
    );
  }

  const inputVal = latestValue(inputTokens.data);
  const cacheVal = latestValue(cacheRead.data);
  const outputVal = latestValue(outputTokens.data);
  const cacheWriteVal = latestValue(cacheWrite.data);
  const compositionTotal = inputVal + cacheVal + outputVal;

  const inputPct = compositionTotal > 0 ? (inputVal / compositionTotal) * 100 : 33;
  const cachePct = compositionTotal > 0 ? (cacheVal / compositionTotal) * 100 : 33;
  const outputPct = compositionTotal > 0 ? (outputVal / compositionTotal) * 100 : 34;

  const modelBars = seriesToBars(
    byModel.data?.series ?? [],
    'model',
    (v) => formatKpi(v, 'count'),
  );

  const cacheHitVal = latestValue(cacheHitRate.data);
  const cacheStatus = cacheHitVal >= 0.5 ? 'ok' : cacheHitVal >= 0.3 ? 'warning' : 'neutral';

  return (
    <div className="space-y-6">
      <PageHeader title="Tokens" subtitle="Token volume by model and agent" />

      <Section title="Token Metrics" kicker="01">
        <PanelGrid columns={4}>
          <KpiCard
            title="Input Tokens"
            description="Total tokens sent to the LLM as prompt context across all sessions. Shows 0 when no agent conversations have occurred in the selected time range."
            value={formatKpi(inputVal, 'count')}
            sparklineData={inputTokens.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Output Tokens"
            description="Total tokens generated by the LLM in completions across all sessions. Shows 0 when no agent responses have been produced in the selected time range."
            value={formatKpi(outputVal, 'count')}
            sparklineData={outputTokens.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Cache Read"
            description="Tokens served from the prompt cache instead of being reprocessed by the LLM. Shows 0 when caching is disabled or no cache hits have occurred."
            value={formatKpi(cacheVal, 'count')}
            sparklineData={cacheRead.data?.series[0]?.dataPoints}
          />
          <KpiCard
            title="Cache Write"
            description="Tokens written into the prompt cache for future reuse. Shows 0 when caching is disabled or no new cache entries have been created."
            value={formatKpi(cacheWriteVal, 'count')}
            sparklineData={cacheWrite.data?.series[0]?.dataPoints}
          />
        </PanelGrid>
      </Section>

      <Section title="Throughput" kicker="02">
        <PanelGrid columns={2}>
          <PanelCard title="Input Token Rate" description="Tokens per minute">
            <TimeSeriesChart series={inputRate.data?.series ?? []} unit="tokens/min" />
          </PanelCard>
          <PanelCard title="Output Token Rate" description="Tokens per minute">
            <TimeSeriesChart series={outputRate.data?.series ?? []} unit="tokens/min" />
          </PanelCard>
        </PanelGrid>
      </Section>

      <Section title="Distribution" kicker="03">
        <PanelGrid columns={2}>
          <PanelCard title="Distribution by Model">
            <HBarList items={modelBars} colourBy="category" />
          </PanelCard>
          <MetricPanel
            title="Cache Efficiency"
            value={`${(cacheHitVal * 100).toFixed(0)}%`}
            description="cache hit rate"
            status={cacheStatus}
            sparklineData={cacheHitRate.data?.series[0]?.dataPoints}
          />
        </PanelGrid>
      </Section>

      <Section title="Token Composition" kicker="04">
        <div className="bg-card border border-border rounded-lg p-4">
          <div className="flex gap-0 h-6 rounded overflow-hidden mb-3">
            <div
              className="h-full bg-[var(--chart-1)]"
              style={{ width: `${inputPct}%` }}
            />
            <div
              className="h-full bg-[var(--chart-2)]"
              style={{ width: `${cachePct}%` }}
            />
            <div
              className="h-full bg-[var(--chart-3)]"
              style={{ width: `${outputPct}%` }}
            />
          </div>
          <div className="flex gap-6 text-xs font-mono tabular-nums">
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[var(--chart-1)]" />
              Input {formatKpi(inputVal, 'count')}
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[var(--chart-2)]" />
              Cache {formatKpi(cacheVal, 'count')}
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-[var(--chart-3)]" />
              Output {formatKpi(outputVal, 'count')}
            </span>
          </div>
        </div>
      </Section>
    </div>
  );
}
