import type { MetricCatalogEntry } from '@/api/types';
import { costTotalQuery, costRateQuery, costByQuery } from './costQueries';

export const metricCatalog: Record<string, MetricCatalogEntry> = {
  // --- Overview ---
  tokens_per_minute: { id: 'tokens_per_minute', title: 'Tokens / Minute', description: 'Rate of total token consumption', query: 'rate(agentic_harness_agent_tokens_total_sum[5m]) * 60', chartType: 'stat', unit: 'tokens/min', category: 'overview', refreshIntervalSeconds: 15 },
  active_sessions: { id: 'active_sessions', title: 'Active Sessions', description: 'Sessions with recent activity', query: 'sum(agentic_harness_agent_session_active) or vector(0)', chartType: 'stat', unit: 'sessions', category: 'overview', refreshIntervalSeconds: 15 },
  cost_today: { id: 'cost_today', title: 'Cost Today', description: 'LLM cost since midnight UTC (provider-reported where available, else estimated)', query: costTotalQuery, chartType: 'stat', unit: 'usd', category: 'overview', refreshIntervalSeconds: 30 },
  cache_hit_rate: { id: 'cache_hit_rate', title: 'Cache Hit Rate', description: 'Prompt cache hit ratio', query: 'agentic_harness_agent_tokens_cache_hit_rate_sum / agentic_harness_agent_tokens_cache_hit_rate_count or vector(0)', chartType: 'gauge', unit: 'percent', category: 'overview', refreshIntervalSeconds: 30 },
  safety_violations: { id: 'safety_violations', title: 'Safety Evaluations', description: 'Content safety evaluations performed', query: 'sum(agentic_harness_agent_safety_evaluations_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'overview', refreshIntervalSeconds: 30 },
  budget_status: { id: 'budget_status', title: 'Budget Status', description: 'Current budget utilization percentage', query: 'max(agentic_harness_agent_budget_utilization_percent) or vector(0)', chartType: 'gauge', unit: 'percent', category: 'overview', refreshIntervalSeconds: 15 },

  // --- Tokens ---
  tokens_input_total: { id: 'tokens_input_total', title: 'Input Tokens', description: 'Total input (prompt) tokens consumed', query: 'sum(agentic_harness_agent_tokens_input_sum) or vector(0)', chartType: 'stat', unit: 'tokens', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_output_total: { id: 'tokens_output_total', title: 'Output Tokens', description: 'Total output (completion) tokens generated', query: 'sum(agentic_harness_agent_tokens_output_sum) or vector(0)', chartType: 'stat', unit: 'tokens', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_cache_read: { id: 'tokens_cache_read', title: 'Cache Read Tokens', description: 'Tokens served from prompt cache', query: 'sum(agentic_harness_agent_tokens_cache_read_total) or vector(0)', chartType: 'stat', unit: 'tokens', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_cache_write: { id: 'tokens_cache_write', title: 'Cache Write Tokens', description: 'Tokens written to prompt cache', query: 'sum(agentic_harness_agent_tokens_cache_write_total) or vector(0)', chartType: 'stat', unit: 'tokens', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_input_rate: { id: 'tokens_input_rate', title: 'Input Token Rate', description: 'Input tokens per minute over time', query: 'rate(agentic_harness_agent_tokens_input_sum[5m]) * 60', chartType: 'timeseries', unit: 'tokens/min', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_output_rate: { id: 'tokens_output_rate', title: 'Output Token Rate', description: 'Output tokens per minute over time', query: 'rate(agentic_harness_agent_tokens_output_sum[5m]) * 60', chartType: 'timeseries', unit: 'tokens/min', category: 'tokens', refreshIntervalSeconds: 15 },
  tokens_by_model: { id: 'tokens_by_model', title: 'Tokens by Model', description: 'Token distribution across models', query: 'sum by (model) (agentic_harness_agent_tokens_total_sum)', chartType: 'pie', unit: 'tokens', category: 'tokens', refreshIntervalSeconds: 30 },
  tokens_cache_hit_rate_ts: { id: 'tokens_cache_hit_rate_ts', title: 'Cache Hit Rate Over Time', description: 'Cache hit ratio over time', query: 'agentic_harness_agent_tokens_cache_hit_rate_sum / agentic_harness_agent_tokens_cache_hit_rate_count', chartType: 'timeseries', unit: 'percent', category: 'tokens', refreshIntervalSeconds: 30 },

  // --- Cost ---
  cost_total: { id: 'cost_total', title: 'Total Cost', description: 'Cumulative LLM spend (provider-reported where available, else estimated)', query: costTotalQuery, chartType: 'stat', unit: 'usd', category: 'cost', refreshIntervalSeconds: 30 },
  cost_rate: { id: 'cost_rate', title: 'Cost Rate', description: 'USD burn rate per hour (provider-reported where available, else estimated)', query: costRateQuery, chartType: 'timeseries', unit: 'usd', category: 'cost', refreshIntervalSeconds: 30 },
  cost_by_model: { id: 'cost_by_model', title: 'Cost by Model', description: 'Cost breakdown per model (provider-reported where available, else estimated)', query: costByQuery('model'), chartType: 'pie', unit: 'usd', category: 'cost', refreshIntervalSeconds: 30 },
  cost_cache_savings: { id: 'cost_cache_savings', title: 'Cache Savings', description: 'Estimated cost saved via prompt caching', query: 'sum(agentic_harness_agent_tokens_cost_cache_savings_total) or vector(0)', chartType: 'stat', unit: 'usd', category: 'cost', refreshIntervalSeconds: 30 },
  cost_budget_remaining: { id: 'cost_budget_remaining', title: 'Budget Remaining', description: 'Remaining budget allocation', query: 'max(agentic_harness_agent_budget_remaining) or vector(0)', chartType: 'gauge', unit: 'usd', category: 'cost', refreshIntervalSeconds: 15 },

  // --- Sessions ---
  sessions_total: { id: 'sessions_total', title: 'Total Sessions', description: 'Lifetime session count', query: 'sum(agentic_harness_agent_session_started_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'sessions', refreshIntervalSeconds: 30 },
  sessions_active: { id: 'sessions_active', title: 'Active Sessions', description: 'Currently active sessions', query: 'sum(agentic_harness_agent_session_active) or vector(0)', chartType: 'stat', unit: 'count', category: 'sessions', refreshIntervalSeconds: 15 },
  sessions_turns_avg: { id: 'sessions_turns_avg', title: 'Avg Turns/Session', description: 'Average conversation turns per session', query: 'agentic_harness_agent_orchestration_turns_per_conversation_sum / agentic_harness_agent_orchestration_turns_per_conversation_count or vector(0)', chartType: 'stat', unit: 'turns', category: 'sessions', refreshIntervalSeconds: 30 },
  sessions_duration_avg: { id: 'sessions_duration_avg', title: 'Avg Duration', description: 'Average session duration', query: 'agentic_harness_agent_orchestration_conversation_duration_sum / agentic_harness_agent_orchestration_conversation_duration_count or vector(0)', chartType: 'stat', unit: 'ms', category: 'sessions', refreshIntervalSeconds: 30 },
  sessions_active_ts: { id: 'sessions_active_ts', title: 'Active Sessions Over Time', description: 'Session concurrency over time', query: 'agentic_harness_agent_session_active or vector(0)', chartType: 'timeseries', unit: 'count', category: 'sessions', refreshIntervalSeconds: 15 },
  sessions_turns_ts: { id: 'sessions_turns_ts', title: 'Turns Over Time', description: 'Conversation turns per minute', query: 'rate(agentic_harness_agent_orchestration_turns_total[5m]) * 60', chartType: 'timeseries', unit: 'turns/min', category: 'sessions', refreshIntervalSeconds: 15 },

  // --- Tools (instrumented via AgentFrameworkSpanProcessor — emits on tool execution) ---
  tools_calls_total: { id: 'tools_calls_total', title: 'Tool Calls', description: 'Total tool invocations', query: 'sum(agentic_harness_agent_tool_invocations_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'tools', refreshIntervalSeconds: 15 },
  tools_errors_total: { id: 'tools_errors_total', title: 'Tool Errors', description: 'Total tool execution errors', query: 'sum(agentic_harness_agent_tool_errors_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'tools', refreshIntervalSeconds: 15 },
  tools_avg_latency: { id: 'tools_avg_latency', title: 'Avg Latency', description: 'Average tool execution time', query: 'agentic_harness_agent_tool_duration_sum / agentic_harness_agent_tool_duration_count or vector(0)', chartType: 'stat', unit: 'ms', category: 'tools', refreshIntervalSeconds: 15 },
  tools_result_size: { id: 'tools_result_size', title: 'Avg Result Size', description: 'Average tool result size in characters', query: 'agentic_harness_agent_tool_result_size_sum / agentic_harness_agent_tool_result_size_count or vector(0)', chartType: 'stat', unit: 'chars', category: 'tools', refreshIntervalSeconds: 30 },
  tools_calls_by_tool: { id: 'tools_calls_by_tool', title: 'Calls by Tool', description: 'Invocation count per tool', query: 'sum by (agent_tool_name) (agentic_harness_agent_tool_invocations_total)', chartType: 'bar', unit: 'count', category: 'tools', refreshIntervalSeconds: 30 },
  tools_latency_by_tool: { id: 'tools_latency_by_tool', title: 'Latency by Tool', description: 'Average latency per tool', query: 'sum by (agent_tool_name) (agentic_harness_agent_tool_duration_sum) / sum by (agent_tool_name) (agentic_harness_agent_tool_duration_count)', chartType: 'bar', unit: 'ms', category: 'tools', refreshIntervalSeconds: 30 },
  tools_error_rate: { id: 'tools_error_rate', title: 'Error Rate Over Time', description: 'Tool error rate trend', query: 'rate(agentic_harness_agent_tool_errors_total[5m]) / (rate(agentic_harness_agent_tool_invocations_total[5m]) > 0)', chartType: 'timeseries', unit: 'percent', category: 'tools', refreshIntervalSeconds: 15 },

  // --- Safety ---
  safety_total: { id: 'safety_total', title: 'Safety Evaluations', description: 'Cumulative content safety evaluations', query: 'sum(agentic_harness_agent_safety_evaluations_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'safety', refreshIntervalSeconds: 30 },
  safety_blocked: { id: 'safety_blocked', title: 'Blocked Requests', description: 'Requests blocked by content safety', query: 'sum(agentic_harness_agent_safety_blocks_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'safety', refreshIntervalSeconds: 30 },
  safety_checks_total: { id: 'safety_checks_total', title: 'Safety Checks', description: 'Total content safety evaluations', query: 'sum(agentic_harness_agent_safety_evaluations_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'safety', refreshIntervalSeconds: 30 },
  safety_violations_ts: { id: 'safety_violations_ts', title: 'Evaluations Over Time', description: 'Safety evaluation trend', query: 'rate(agentic_harness_agent_safety_evaluations_total[5m]) * 60', chartType: 'timeseries', unit: 'count/min', category: 'safety', refreshIntervalSeconds: 15 },
  safety_by_category: { id: 'safety_by_category', title: 'Evaluations by Category', description: 'Breakdown by evaluation type', query: 'sum by (category) (agentic_harness_agent_safety_evaluations_total)', chartType: 'pie', unit: 'count', category: 'safety', refreshIntervalSeconds: 30 },
  safety_block_rate: { id: 'safety_block_rate', title: 'Block Rate', description: 'Percentage of requests blocked', query: 'sum(agentic_harness_agent_safety_blocks_total) / (sum(agentic_harness_agent_safety_evaluations_total) > 0)', chartType: 'gauge', unit: 'percent', category: 'safety', refreshIntervalSeconds: 30 },

  // --- RAG ---
  rag_ingestion_total: { id: 'rag_ingestion_total', title: 'Documents Ingested', description: 'Total documents processed for RAG', query: 'sum(agentic_harness_rag_ingestion_documents_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'rag', refreshIntervalSeconds: 30 },
  rag_retrieval_total: { id: 'rag_retrieval_total', title: 'Retrievals', description: 'Total RAG retrieval operations', query: 'sum(agentic_harness_rag_retrieval_queries_total) or vector(0)', chartType: 'stat', unit: 'count', category: 'rag', refreshIntervalSeconds: 15 },
  rag_avg_latency: { id: 'rag_avg_latency', title: 'Avg Retrieval Latency', description: 'Average RAG retrieval time', query: 'agentic_harness_rag_retrieval_duration_sum / agentic_harness_rag_retrieval_duration_count or vector(0)', chartType: 'stat', unit: 'ms', category: 'rag', refreshIntervalSeconds: 15 },
  rag_chunks_avg: { id: 'rag_chunks_avg', title: 'Avg Chunks Returned', description: 'Average chunks per retrieval', query: 'agentic_harness_rag_retrieval_chunks_returned_sum / agentic_harness_rag_retrieval_chunks_returned_count or vector(0)', chartType: 'stat', unit: 'chunks', category: 'rag', refreshIntervalSeconds: 30 },
  rag_ingestion_rate: { id: 'rag_ingestion_rate', title: 'Ingestion Rate', description: 'Document ingestion throughput', query: 'rate(agentic_harness_rag_ingestion_documents_total[5m]) * 60', chartType: 'timeseries', unit: 'docs/min', category: 'rag', refreshIntervalSeconds: 15 },
  rag_retrieval_latency_ts: { id: 'rag_retrieval_latency_ts', title: 'Retrieval Latency Over Time', description: 'RAG retrieval latency trend', query: 'agentic_harness_rag_retrieval_duration_sum / agentic_harness_rag_retrieval_duration_count', chartType: 'timeseries', unit: 'ms', category: 'rag', refreshIntervalSeconds: 15 },
  rag_by_source: { id: 'rag_by_source', title: 'Top Sources', description: 'Most-retrieved document sources', query: 'topk(10, sum by (source) (agentic_harness_rag_retrieval_queries_total))', chartType: 'bar', unit: 'count', category: 'rag', refreshIntervalSeconds: 30 },

  // --- Budget (instrumented via BudgetTrackingService observable gauges) ---
  budget_spent: { id: 'budget_spent', title: 'Total Spent', description: 'Total budget consumed', query: 'agentic_harness_agent_budget_current_spend or vector(0)', chartType: 'stat', unit: 'usd', category: 'budget', refreshIntervalSeconds: 15 },
  budget_limit: { id: 'budget_limit', title: 'Budget Limit', description: 'Configured budget ceiling', query: 'agentic_harness_agent_budget_threshold_critical or vector(0)', chartType: 'stat', unit: 'usd', category: 'budget', refreshIntervalSeconds: 60 },
  budget_remaining: { id: 'budget_remaining', title: 'Remaining', description: 'Budget remaining before limit', query: 'agentic_harness_agent_budget_threshold_critical - agentic_harness_agent_budget_current_spend or vector(0)', chartType: 'stat', unit: 'usd', category: 'budget', refreshIntervalSeconds: 15 },
  budget_utilization: { id: 'budget_utilization', title: 'Utilization', description: 'Budget utilization percentage', query: 'agentic_harness_agent_budget_current_spend / agentic_harness_agent_budget_threshold_critical or vector(0)', chartType: 'gauge', unit: 'percent', category: 'budget', refreshIntervalSeconds: 15 },
  budget_spend_rate: { id: 'budget_spend_rate', title: 'Spend Rate', description: 'Budget burn rate over time (provider-reported where available, else estimated)', query: costRateQuery, chartType: 'timeseries', unit: 'usd/hr', category: 'budget', refreshIntervalSeconds: 15 },
  budget_status: { id: 'budget_status', title: 'Budget Status', description: 'Budget status (0=clear, 1=warning, 2=critical)', query: 'agentic_harness_agent_budget_status or vector(0)', chartType: 'stat', unit: 'status', category: 'budget', refreshIntervalSeconds: 30 },

  // --- Governance ---
  governance_decisions: { id: 'governance_decisions', title: 'Policy Decisions', description: 'Total governance policy evaluations', query: 'sum(increase(agentic_harness_agent_governance_decisions_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_violations: { id: 'governance_violations', title: 'Violations', description: 'Denied actions by governance policy', query: 'sum(increase(agentic_harness_agent_governance_violations_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_eval_duration: { id: 'governance_eval_duration', title: 'Eval Latency', description: 'Policy evaluation duration (p50)', query: 'histogram_quantile(0.5, sum(rate(agentic_harness_agent_governance_evaluation_duration_bucket[5m])) by (le)) or vector(0)', chartType: 'stat', unit: 'ms', category: 'governance', refreshIntervalSeconds: 15 },
  governance_rate_limit_hits: { id: 'governance_rate_limit_hits', title: 'Rate Limit Hits', description: 'Rate-limited tool calls', query: 'sum(increase(agentic_harness_agent_governance_rate_limit_hits_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_audit_events: { id: 'governance_audit_events', title: 'Audit Events', description: 'Governance audit log entries', query: 'sum(increase(agentic_harness_agent_governance_audit_events_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_injection_detections: { id: 'governance_injection_detections', title: 'Injection Detections', description: 'Prompt injection attempts detected', query: 'sum(increase(agentic_harness_agent_governance_injection_detections_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_mcp_scans: { id: 'governance_mcp_scans', title: 'MCP Scans', description: 'MCP tool security scans performed', query: 'sum(increase(agentic_harness_agent_governance_mcp_scans_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_mcp_threats: { id: 'governance_mcp_threats', title: 'MCP Threats', description: 'MCP tool threats detected', query: 'sum(increase(agentic_harness_agent_governance_mcp_threats_total[5m])) or vector(0)', chartType: 'stat', unit: 'count', category: 'governance', refreshIntervalSeconds: 15 },
  governance_decisions_ts: { id: 'governance_decisions_ts', title: 'Decisions Over Time', description: 'Policy decisions rate by action', query: 'sum(rate(agentic_harness_agent_governance_decisions_total[1m])) by (agent_governance_action)', chartType: 'timeseries', unit: 'decisions/min', category: 'governance', refreshIntervalSeconds: 15 },
  governance_violations_by_tool: { id: 'governance_violations_by_tool', title: 'Violations by Tool', description: 'Blocked tool calls by tool name', query: 'topk(10, sum(increase(agentic_harness_agent_governance_violations_total[1h])) by (agent_governance_tool))', chartType: 'bar', unit: 'count', category: 'governance', refreshIntervalSeconds: 30 },
  governance_injections_ts: { id: 'governance_injections_ts', title: 'Injections Over Time', description: 'Prompt injection detections rate', query: 'sum(rate(agentic_harness_agent_governance_injection_detections_total[1m])) or vector(0)', chartType: 'timeseries', unit: 'detections/min', category: 'governance', refreshIntervalSeconds: 15 },
};

export function getCatalogByCategory(category: string): MetricCatalogEntry[] {
  return Object.values(metricCatalog).filter((e) => e.category === category);
}
