namespace Domain.AI.Telemetry.Conventions;

/// <summary>RAG pipeline telemetry attributes and metric names.</summary>
public static class RagConventions
{
    // ── Attribute constants ──────────────────────────────────────────

    /// <summary>Query classification type (e.g., simple_lookup, multi_hop, global_thematic).</summary>
    public const string QueryType = "rag.query_type";

    /// <summary>Retrieval strategy used for this query (e.g., hybrid_vector_bm25, graph_rag).</summary>
    public const string RetrievalStrategy = "rag.retrieval.strategy";

    /// <summary>Retrieval latency in milliseconds (histogram attribute).</summary>
    public const string RetrievalLatencyMs = "rag.retrieval.latency_ms";

    /// <summary>Number of chunks returned by the retriever before reranking.</summary>
    public const string RetrievalChunksReturned = "rag.retrieval.chunks_returned";

    /// <summary>Reranker strategy applied (e.g., azure_semantic, cross_encoder, none).</summary>
    public const string RerankStrategy = "rag.rerank.strategy";

    /// <summary>Rerank relevance score (histogram attribute, 0-1 range).</summary>
    public const string RerankScore = "rag.rerank.score";

    /// <summary>CRAG correction action taken (accept, refine, web_fallback, reject).</summary>
    public const string CragAction = "rag.crag.action";

    /// <summary>CRAG relevance score used to determine the correction action (0-1 range).</summary>
    public const string CragScore = "rag.crag.score";

    /// <summary>Number of chunks produced during document ingestion.</summary>
    public const string IngestChunksProduced = "rag.ingest.chunks_produced";

    /// <summary>Number of tokens sent to the embedding model during ingestion.</summary>
    public const string IngestTokensEmbedded = "rag.ingest.tokens_embedded";

    /// <summary>GraphRAG community level used for retrieval (0 = most granular).</summary>
    public const string GraphCommunityLevel = "rag.graph.community_level";

    /// <summary>Number of communities detected at the current level.</summary>
    public const string GraphCommunityCount = "rag.graph.community_count";

    /// <summary>Graph traversal depth used for local search.</summary>
    public const string GraphTraversalDepth = "rag.graph.traversal_depth";

    /// <summary>Number of query variants generated by RAG-Fusion.</summary>
    public const string FusionVariantCount = "rag.fusion.variant_count";

    /// <summary>Model tier used for this RAG operation (premium, standard, economy).</summary>
    public const string ModelTier = "rag.model.tier";

    /// <summary>Azure OpenAI deployment name used for this RAG operation.</summary>
    public const string ModelDeployment = "rag.model.deployment";

    /// <summary>RAG operation name (e.g., contextual_enrichment, crag_evaluation, query_classification).</summary>
    public const string ModelOperation = "rag.model.operation";

    /// <summary>Number of memory operations performed (remember/recall/forget/improve).</summary>
    public const string MemoryOperationCount = "rag.memory.operation_count";

    /// <summary>Type of memory operation performed.</summary>
    public const string MemoryOperationType = "rag.memory.operation_type";

    /// <summary>Number of memories returned from a recall operation.</summary>
    public const string MemoryRecallCount = "rag.memory.recall_count";

    /// <summary>Session-local memory cache hit rate (0.0-1.0).</summary>
    public const string MemoryCacheHitRate = "rag.memory.cache_hit_rate";

    /// <summary>Number of memories decayed during a decay pass.</summary>
    public const string MemoryDecayCount = "rag.memory.decay_count";

    /// <summary>Number of memories pruned during a pruning pass.</summary>
    public const string MemoryPruneCount = "rag.memory.prune_count";

    /// <summary>Weight delta applied during a memory improve operation.</summary>
    public const string MemoryWeightDelta = "rag.memory.weight_delta";

    /// <summary>Number of feedback weights persisted back to the graph backend.</summary>
    public const string FeedbackPersistCount = "rag.feedback.persist_count";

    // ── Metric name constants ────────────────────────────────────────

    /// <summary>Histogram: end-to-end document ingestion duration in milliseconds.</summary>
    public const string IngestionDuration = "rag.ingestion.duration";

    /// <summary>Histogram: retrieval pipeline duration in seconds (vector search + BM25 + fusion).</summary>
    public const string RetrievalDuration = "rag.retrieval.duration";

    /// <summary>Histogram: reranking pass duration in seconds.</summary>
    public const string RerankDuration = "rag.rerank.duration";

    /// <summary>Counter: total CRAG relevance evaluations performed.</summary>
    public const string CragEvaluations = "rag.crag.evaluations";

    /// <summary>Counter: total documents ingested into the RAG pipeline.</summary>
    public const string IngestionDocuments = "rag.ingestion.documents";

    /// <summary>Counter: total retrieval queries executed.</summary>
    public const string RetrievalQueries = "rag.retrieval.queries";

    /// <summary>Counter: total RAG-Fusion query variants generated.</summary>
    public const string FusionQueriesGenerated = "rag.fusion.queries_generated";

    /// <summary>Counter: retrieval queries that returned at least one relevant chunk.</summary>
    public const string RetrievalHits = "rag.retrieval.hits";
    /// <summary>Counter: per-source retrieval queries. Tags: rag.source.name.</summary>
    public const string SourceRetrievals = "rag.source.retrievals";
    /// <summary>Histogram: grounding score (0-1) — fraction of turns citing retrieved chunks.</summary>
    public const string GroundingScore = "rag.grounding.score";
    /// <summary>Source name tag for per-source metrics.</summary>
    public const string SourceName = "rag.source.name";

    /// <summary>Counter: total memory operations across all types.</summary>
    public const string MemoryOperations = "rag.memory.operations";

    /// <summary>Histogram: memory recall latency in milliseconds.</summary>
    public const string MemoryRecallLatency = "rag.memory.recall.latency";

    /// <summary>Counter: community detection runs completed.</summary>
    public const string CommunityDetectionRuns = "rag.graph.community_detection.runs";

    /// <summary>Histogram: community detection duration in seconds.</summary>
    public const string CommunityDetectionDuration = "rag.graph.community_detection.duration";

    // ── Multi-source attributes ─────────────────────────────────────

    /// <summary>Number of sources queried in a multi-source retrieval.</summary>
    public const string MultiSourceCount = "rag.multi_source.source_count";

    /// <summary>Query complexity tier used for source selection.</summary>
    public const string MultiSourceComplexity = "rag.multi_source.complexity";

    /// <summary>Per-source latency in milliseconds.</summary>
    public const string MultiSourceLatency = "rag.multi_source.latency_ms";

    // ── Quality evaluation attributes ───────────────────────────────

    /// <summary>Context precision score (0-1) from quality evaluation.</summary>
    public const string QualityContextPrecision = "rag.quality.context_precision";

    /// <summary>Context recall score (0-1) from quality evaluation.</summary>
    public const string QualityContextRecall = "rag.quality.context_recall";

    /// <summary>Faithfulness score (0-1) from quality evaluation.</summary>
    public const string QualityFaithfulness = "rag.quality.faithfulness";

    /// <summary>Answer relevancy score (0-1) from quality evaluation.</summary>
    public const string QualityAnswerRelevancy = "rag.quality.answer_relevancy";

    /// <summary>Overall quality score (0-1) from quality evaluation.</summary>
    public const string QualityOverallScore = "rag.quality.overall_score";

    // ── Cost tracking attributes ────────────────────────────────────

    /// <summary>Total tokens consumed in a retrieval execution.</summary>
    public const string CostTotalTokens = "rag.cost.total_tokens";

    /// <summary>Prompt tokens consumed in a retrieval execution.</summary>
    public const string CostPromptTokens = "rag.cost.prompt_tokens";

    /// <summary>Completion tokens consumed in a retrieval execution.</summary>
    public const string CostCompletionTokens = "rag.cost.completion_tokens";

    /// <summary>Estimated cost in USD for a retrieval execution.</summary>
    public const string CostEstimatedUsd = "rag.cost.estimated_usd";

    // ── Multi-source metric name constants ──────────────────────────

    /// <summary>Histogram: multi-source orchestration total duration in milliseconds.</summary>
    public const string MultiSourceDuration = "rag.multi_source.duration";

    /// <summary>Histogram: per-source retrieval latency in milliseconds.</summary>
    public const string MultiSourcePerSourceLatency = "rag.multi_source.per_source_latency";

    /// <summary>Counter: total multi-source orchestration invocations.</summary>
    public const string MultiSourceInvocations = "rag.multi_source.invocations";

    // ── Quality metric name constants ───────────────────────────────

    /// <summary>Histogram: overall quality scores from evaluations.</summary>
    public const string QualityScoreHistogram = "rag.quality.overall_score_histogram";

    /// <summary>Counter: total quality evaluations performed.</summary>
    public const string QualityEvaluations = "rag.quality.evaluations";

    // ── Cost metric name constants ──────────────────────────────────

    /// <summary>Counter: total tokens consumed across all retrieval operations.</summary>
    public const string CostTokensTotal = "rag.cost.tokens_total";

    /// <summary>Histogram: estimated cost per retrieval execution in USD.</summary>
    public const string CostPerExecution = "rag.cost.per_execution";

    // ── Web search source attributes ───────────────────────────────

    /// <summary>Web search provider name (e.g., "bing", "tavily").</summary>
    public const string WebSearchProvider = "rag.web_search.provider";

    /// <summary>Number of results returned by the web search provider.</summary>
    public const string WebSearchResultCount = "rag.web_search.result_count";

    /// <summary>Web search provider latency in milliseconds.</summary>
    public const string WebSearchLatency = "rag.web_search.latency_ms";

    // ── SQL database source attributes ─────────────────────────────

    /// <summary>SQL template name matched (empty if LLM-generated).</summary>
    public const string SqlSourceTemplate = "rag.sql.template_name";

    /// <summary>Whether the SQL query was from a template (true) or LLM-generated (false).</summary>
    public const string SqlSourceWasTemplate = "rag.sql.was_template_match";

    /// <summary>Number of rows returned by the SQL query.</summary>
    public const string SqlSourceRowCount = "rag.sql.row_count";

    /// <summary>SQL query execution latency in milliseconds.</summary>
    public const string SqlSourceLatency = "rag.sql.latency_ms";

    // ── Value sets ───────────────────────────────────────────────────

    /// <summary>Well-known values for <see cref="QueryType"/>.</summary>
    public static class QueryTypeValues
    {
        /// <summary>Direct fact lookup requiring a single retrieval pass.</summary>
        public const string SimpleLookup = "simple_lookup";

        /// <summary>Multi-hop reasoning across multiple chunks or documents.</summary>
        public const string MultiHop = "multi_hop";

        /// <summary>Global thematic query requiring community-level summarization (GraphRAG).</summary>
        public const string GlobalThematic = "global_thematic";

        /// <summary>Comparative query requiring retrieval from multiple entity clusters.</summary>
        public const string Comparative = "comparative";

        /// <summary>Adversarial or out-of-distribution query designed to test guardrails.</summary>
        public const string Adversarial = "adversarial";
    }

    /// <summary>Well-known values for <see cref="RetrievalStrategy"/>.</summary>
    public static class StrategyValues
    {
        /// <summary>Hybrid retrieval combining dense vector search with BM25 keyword matching.</summary>
        public const string HybridVectorBm25 = "hybrid_vector_bm25";

        /// <summary>Graph-based retrieval using community summaries and entity relationships.</summary>
        public const string GraphRag = "graph_rag";

        /// <summary>RAPTOR tree-based retrieval with hierarchical summarization.</summary>
        public const string RaptorTree = "raptor_tree";

        /// <summary>Multi-query fusion (RAG-Fusion) generating variant queries and merging results via RRF.</summary>
        public const string MultiQueryFusion = "multi_query_fusion";
    }

    /// <summary>Well-known values for <see cref="CragAction"/>.</summary>
    public static class CragActionValues
    {
        /// <summary>Retrieved chunks are sufficiently relevant; use as-is.</summary>
        public const string Accept = "accept";

        /// <summary>Retrieved chunks are partially relevant; refine with targeted re-retrieval.</summary>
        public const string Refine = "refine";

        /// <summary>Retrieved chunks are irrelevant; fall back to web search.</summary>
        public const string WebFallback = "web_fallback";

        /// <summary>Retrieved chunks are irrelevant and no fallback is available; reject the query.</summary>
        public const string Reject = "reject";
    }

    /// <summary>Well-known values for <see cref="ModelTier"/>.</summary>
    public static class ModelTierValues
    {
        /// <summary>Premium tier: highest-capability model for complex reasoning tasks.</summary>
        public const string Premium = "premium";

        /// <summary>Standard tier: balanced model for general-purpose RAG operations.</summary>
        public const string Standard = "standard";

        /// <summary>Economy tier: fast/cheap model for simple classification and extraction.</summary>
        public const string Economy = "economy";
    }

    /// <summary>Well-known values for <see cref="MemoryOperationType"/>.</summary>
    public static class MemoryOperationValues
    {
        /// <summary>A fact was stored in the memory store.</summary>
        public const string Remember = "remember";

        /// <summary>Knowledge was retrieved from the memory store.</summary>
        public const string Recall = "recall";

        /// <summary>A specific fact was deleted from the memory store.</summary>
        public const string Forget = "forget";

        /// <summary>Feedback was applied to improve memory quality.</summary>
        public const string Improve = "improve";
    }
}
